/**
 * Swappy REST API
 * This is Swappy's REST API. See below for all available endpoints. This is an <strong>alpha version</strong> and might still be subject to change
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ProductBulkResponse', 'model/ValidationError'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ProductBulkResponse'), require('./ValidationError'));
  } else {
    // Browser globals (root is window)
    if (!root.SwappyRestApi) {
      root.SwappyRestApi = {};
    }
    root.SwappyRestApi.BulkJobResult = factory(root.SwappyRestApi.ApiClient, root.SwappyRestApi.ProductBulkResponse, root.SwappyRestApi.ValidationError);
  }
}(this, function(ApiClient, ProductBulkResponse, ValidationError) {
  'use strict';




  /**
   * The BulkJobResult model module.
   * @module model/BulkJobResult
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>BulkJobResult</code>.
   * @alias module:model/BulkJobResult
   * @class
   * @param success {Boolean} 
   */
  var exports = function(success) {
    var _this = this;

    _this['success'] = success;



  };

  /**
   * Constructs a <code>BulkJobResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BulkJobResult} obj Optional instance to populate.
   * @return {module:model/BulkJobResult} The populated <code>BulkJobResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('success')) {
        obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
      }
      if (data.hasOwnProperty('message_id')) {
        obj['message_id'] = ApiClient.convertToType(data['message_id'], 'String');
      }
      if (data.hasOwnProperty('error')) {
        obj['error'] = ValidationError.constructFromObject(data['error']);
      }
      if (data.hasOwnProperty('product')) {
        obj['product'] = ProductBulkResponse.constructFromObject(data['product']);
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} success
   */
  exports.prototype['success'] = undefined;
  /**
   * ID that was/is given with the add request and that will be given back
   * @member {String} message_id
   */
  exports.prototype['message_id'] = undefined;
  /**
   * @member {module:model/ValidationError} error
   */
  exports.prototype['error'] = undefined;
  /**
   * @member {module:model/ProductBulkResponse} product
   */
  exports.prototype['product'] = undefined;



  return exports;
}));


