/**
 * Swappy REST API
 * This is Swappy's REST API. See below for all available endpoints. This is an <strong>alpha version</strong> and might still be subject to change
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SwappyRestApi) {
      root.SwappyRestApi = {};
    }
    root.SwappyRestApi.ProductOffer = factory(root.SwappyRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ProductOffer model module.
   * @module model/ProductOffer
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>ProductOffer</code>.
   * @alias module:model/ProductOffer
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>ProductOffer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductOffer} obj Optional instance to populate.
   * @return {module:model/ProductOffer} The populated <code>ProductOffer</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accept')) {
        obj['accept'] = ApiClient.convertToType(data['accept'], 'Boolean');
      }
      if (data.hasOwnProperty('accept_over')) {
        obj['accept_over'] = ApiClient.convertToType(data['accept_over'], 'Number');
      }
      if (data.hasOwnProperty('refuse_under')) {
        obj['refuse_under'] = ApiClient.convertToType(data['refuse_under'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} accept
   */
  exports.prototype['accept'] = undefined;
  /**
   * @member {Number} accept_over
   */
  exports.prototype['accept_over'] = undefined;
  /**
   * @member {Number} refuse_under
   */
  exports.prototype['refuse_under'] = undefined;



  return exports;
}));


