/**
 * Swappy REST API
 * This is Swappy's REST API. See below for all available endpoints. This is an <strong>alpha version</strong> and might still be subject to change
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Product', 'model/BulkJob', 'model/BulkJobResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Product'), require('../model/BulkJob'), require('../model/BulkJobResult'));
  } else {
    // Browser globals (root is window)
    if (!root.SwappyRestApi) {
      root.SwappyRestApi = {};
    }
    root.SwappyRestApi.BulkApi = factory(root.SwappyRestApi.ApiClient, root.SwappyRestApi.Product, root.SwappyRestApi.BulkJob, root.SwappyRestApi.BulkJobResult);
  }
}(this, function(ApiClient, Product, BulkJob, BulkJobResult) {
  'use strict';

  /**
   * Bulk service.
   * @module api/BulkApi
   * @version 0.1.0
   */

  /**
   * Constructs a new BulkApi. 
   * @alias module:api/BulkApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createBulkJob operation.
     * @callback module:api/BulkApi~createBulkJobCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BulkJob} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Start a bulk product job 
     * @param {Array.<module:model/Product>} body Product list to be uploaded
     * @param {Object} opts Optional parameters
     * @param {String} opts.language Language for the response
     * @param {module:api/BulkApi~createBulkJobCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BulkJob}
     */
    this.createBulkJob = function(body, opts, callback) {
      opts = opts || {};
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw "Missing the required parameter 'body' when calling createBulkJob";
      }


      var pathParams = {
      };
      var queryParams = {
        'language': opts['language']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = BulkJob;

      return this.apiClient.callApi(
        '/v1/bulkjobs', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getBulkJob operation.
     * @callback module:api/BulkApi~getBulkJobCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BulkJob} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get infos about a job 
     * @param {Integer} id Product ID
     * @param {Object} opts Optional parameters
     * @param {String} opts.ifNoneMatch Etag, will return &#x60;304 Not Modified&#x60; if content hasn&#39;t changed
     * @param {Date} opts.ifModifiedSince Will return &#x60;304 Not Modified&#x60; if content hasn&#39;t changed
     * @param {String} opts.language Language for the response
     * @param {module:api/BulkApi~getBulkJobCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BulkJob}
     */
    this.getBulkJob = function(id, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling getBulkJob";
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
        'language': opts['language']
      };
      var headerParams = {
        'If-None-Match': opts['ifNoneMatch'],
        'If-Modified-Since': opts['ifModifiedSince']
      };
      var formParams = {
      };

      var authNames = ['oauth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = BulkJob;

      return this.apiClient.callApi(
        '/v1/bulkjobs/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getBulkJobResult operation.
     * @callback module:api/BulkApi~getBulkJobResultCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/BulkJobResult>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get results for a job
     * @param {Integer} id Product ID
     * @param {Object} opts Optional parameters
     * @param {String} opts.ifNoneMatch Etag, will return &#x60;304 Not Modified&#x60; if content hasn&#39;t changed
     * @param {Date} opts.ifModifiedSince Will return &#x60;304 Not Modified&#x60; if content hasn&#39;t changed
     * @param {String} opts.language Language for the response
     * @param {module:api/BulkApi~getBulkJobResultCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/BulkJobResult>}
     */
    this.getBulkJobResult = function(id, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling getBulkJobResult";
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
        'language': opts['language']
      };
      var headerParams = {
        'If-None-Match': opts['ifNoneMatch'],
        'If-Modified-Since': opts['ifModifiedSince']
      };
      var formParams = {
      };

      var authNames = ['oauth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [BulkJobResult];

      return this.apiClient.callApi(
        '/v1/bulkjobs/{id}/results', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
