/**
 * Swappy REST API
 * This is Swappy's REST API. See below for all available endpoints. This is an <strong>alpha version</strong> and might still be subject to change
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Address', 'model/BulkJob', 'model/BulkJobResult', 'model/Category', 'model/Delivery', 'model/DeliveryType', 'model/Duration', 'model/Error', 'model/FieldError', 'model/InlineResponse200', 'model/InlineResponse2001', 'model/Live', 'model/Member', 'model/Option', 'model/Payment', 'model/Product', 'model/ProductBulkResponse', 'model/ProductEstimate', 'model/ProductImage', 'model/ProductOffer', 'model/ProductTaxes', 'model/ShippingMethod', 'model/ShortAddress', 'model/ShortMember', 'model/ShortProduct', 'model/ShortProductOffer', 'model/TempImage', 'model/ValidationError', 'api/BulkApi', 'api/DataApi', 'api/MiscApi', 'api/OauthApi', 'api/ProductsApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Address'), require('./model/BulkJob'), require('./model/BulkJobResult'), require('./model/Category'), require('./model/Delivery'), require('./model/DeliveryType'), require('./model/Duration'), require('./model/Error'), require('./model/FieldError'), require('./model/InlineResponse200'), require('./model/InlineResponse2001'), require('./model/Live'), require('./model/Member'), require('./model/Option'), require('./model/Payment'), require('./model/Product'), require('./model/ProductBulkResponse'), require('./model/ProductEstimate'), require('./model/ProductImage'), require('./model/ProductOffer'), require('./model/ProductTaxes'), require('./model/ShippingMethod'), require('./model/ShortAddress'), require('./model/ShortMember'), require('./model/ShortProduct'), require('./model/ShortProductOffer'), require('./model/TempImage'), require('./model/ValidationError'), require('./api/BulkApi'), require('./api/DataApi'), require('./api/MiscApi'), require('./api/OauthApi'), require('./api/ProductsApi'));
  }
}(function(ApiClient, Address, BulkJob, BulkJobResult, Category, Delivery, DeliveryType, Duration, Error, FieldError, InlineResponse200, InlineResponse2001, Live, Member, Option, Payment, Product, ProductBulkResponse, ProductEstimate, ProductImage, ProductOffer, ProductTaxes, ShippingMethod, ShortAddress, ShortMember, ShortProduct, ShortProductOffer, TempImage, ValidationError, BulkApi, DataApi, MiscApi, OauthApi, ProductsApi) {
  'use strict';

  /**
   * This_is_Swappys_REST_API__See_below_for_all_available_endpoints__This_is_an_strongalpha_versionstrong_and_might_still_be_subject_to_change.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var SwappyRestApi = require('index'); // See note below*.
   * var xxxSvc = new SwappyRestApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new SwappyRestApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new SwappyRestApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new SwappyRestApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.1.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Address model constructor.
     * @property {module:model/Address}
     */
    Address: Address,
    /**
     * The BulkJob model constructor.
     * @property {module:model/BulkJob}
     */
    BulkJob: BulkJob,
    /**
     * The BulkJobResult model constructor.
     * @property {module:model/BulkJobResult}
     */
    BulkJobResult: BulkJobResult,
    /**
     * The Category model constructor.
     * @property {module:model/Category}
     */
    Category: Category,
    /**
     * The Delivery model constructor.
     * @property {module:model/Delivery}
     */
    Delivery: Delivery,
    /**
     * The DeliveryType model constructor.
     * @property {module:model/DeliveryType}
     */
    DeliveryType: DeliveryType,
    /**
     * The Duration model constructor.
     * @property {module:model/Duration}
     */
    Duration: Duration,
    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error: Error,
    /**
     * The FieldError model constructor.
     * @property {module:model/FieldError}
     */
    FieldError: FieldError,
    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200: InlineResponse200,
    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001: InlineResponse2001,
    /**
     * The Live model constructor.
     * @property {module:model/Live}
     */
    Live: Live,
    /**
     * The Member model constructor.
     * @property {module:model/Member}
     */
    Member: Member,
    /**
     * The Option model constructor.
     * @property {module:model/Option}
     */
    Option: Option,
    /**
     * The Payment model constructor.
     * @property {module:model/Payment}
     */
    Payment: Payment,
    /**
     * The Product model constructor.
     * @property {module:model/Product}
     */
    Product: Product,
    /**
     * The ProductBulkResponse model constructor.
     * @property {module:model/ProductBulkResponse}
     */
    ProductBulkResponse: ProductBulkResponse,
    /**
     * The ProductEstimate model constructor.
     * @property {module:model/ProductEstimate}
     */
    ProductEstimate: ProductEstimate,
    /**
     * The ProductImage model constructor.
     * @property {module:model/ProductImage}
     */
    ProductImage: ProductImage,
    /**
     * The ProductOffer model constructor.
     * @property {module:model/ProductOffer}
     */
    ProductOffer: ProductOffer,
    /**
     * The ProductTaxes model constructor.
     * @property {module:model/ProductTaxes}
     */
    ProductTaxes: ProductTaxes,
    /**
     * The ShippingMethod model constructor.
     * @property {module:model/ShippingMethod}
     */
    ShippingMethod: ShippingMethod,
    /**
     * The ShortAddress model constructor.
     * @property {module:model/ShortAddress}
     */
    ShortAddress: ShortAddress,
    /**
     * The ShortMember model constructor.
     * @property {module:model/ShortMember}
     */
    ShortMember: ShortMember,
    /**
     * The ShortProduct model constructor.
     * @property {module:model/ShortProduct}
     */
    ShortProduct: ShortProduct,
    /**
     * The ShortProductOffer model constructor.
     * @property {module:model/ShortProductOffer}
     */
    ShortProductOffer: ShortProductOffer,
    /**
     * The TempImage model constructor.
     * @property {module:model/TempImage}
     */
    TempImage: TempImage,
    /**
     * The ValidationError model constructor.
     * @property {module:model/ValidationError}
     */
    ValidationError: ValidationError,
    /**
     * The BulkApi service constructor.
     * @property {module:api/BulkApi}
     */
    BulkApi: BulkApi,
    /**
     * The DataApi service constructor.
     * @property {module:api/DataApi}
     */
    DataApi: DataApi,
    /**
     * The MiscApi service constructor.
     * @property {module:api/MiscApi}
     */
    MiscApi: MiscApi,
    /**
     * The OauthApi service constructor.
     * @property {module:api/OauthApi}
     */
    OauthApi: OauthApi,
    /**
     * The ProductsApi service constructor.
     * @property {module:api/ProductsApi}
     */
    ProductsApi: ProductsApi
  };

  return exports;
}));
